### ISSUE TITLE
鱼皮，遇到一个bug

### ISSUE THREAD

**Issue by aze9420** [liyupi/yu-auto-reply#1]
问题：使用Java编写冒泡排序
2023-03-25 15:23:31.057 ERROR 1 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.lang.NullPointerException: null
at com.yupi.autoreply.answerer.OpenAiAnswerer.doAnswer(OpenAiAnswerer.java:37) ~[classes!/:0.0.1-SNAPSHOT]
at com.yupi.autoreply.monitor.ZsxqMonitor.onMonitor(ZsxqMonitor.java:58) ~[classes!/:0.0.1-SNAPSHOT]
at com.yupi.autoreply.job.JobMediator.run(JobMediator.java:29) ~[classes!/:0.0.1-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.22.jar!/:5.3.22]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) [spring-context-5.3.22.jar!/:5.3.22]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_302]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_302]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_302]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_302]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]

**Comment by liyupi** [comment]
我猜测是 openai 接口拒绝了这个回答，现在没有对这个接口做特别严格的校验

**Comment by aze9420** [comment]
> 

嗯嗯好勒，我再看看

**Comment by liyupi** [comment]
> > 
> 
> 嗯嗯好勒，我再看看

感兴趣欢迎贡献，在 api 里补充参数判断和异常提示即可~

**Comment by lingwecho** [comment]
好像是model改成gpt-3.5-turbo就会报这个错，text-davinci-003没问题

**Comment by null0034** [comment]
> 好像是模型改成gpt-3.5-turbo就会报这个错，text-davinci-003没问题

这里需要你去修改请求的URL，openai的对话模型的URL路径应该是/v1/chat/completions
